name: Publish Package to npmjs

on:
  push:
    branches:
      - main

stages:
  - build
  - publish

build:
  image: node:18
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 hour

publish:
  image: node:18
  stage: publish
  only:
    - main
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - cd build/
    - npm publish --access public --dry-run
  environment:
    name: production
